// export const Blog_Overview = [
//   {
//     key: 1,
//     image: require('../../assets/images/blog_ovr1.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 2,
//     image: require('../../assets/images/blog_ovr2.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 3,
//     image: require('../../assets/images/blog_ovr3.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 4,
//     image: require('../../assets/images/blog_ovr4.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 5,
//     image: require('../../assets/images/blog_ovr5.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 6,
//     image: require('../../assets/images/blog_ovr6.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 7,
//     image: require('../../assets/images/blog_ovr7.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 8,
//     image: require('../../assets/images/blog_ovr8.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 9,
//     image: require('../../assets/images/blog_ovr9.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
//   {
//     key: 10,
//     image: require('../../assets/images/blog_ovr10.png'),
//     sub_title: 'Nunc cursus',
//     title: 'FUSCE BIBENDUM LUCTUS DUI VITAE ELEIFEND.',
//     date: '2024-07-25',
//     auth_name: 'Antophy',
//     auth_img: require('../../assets/images/blog_ovr_auth.png'),
//   },
// ];
